services:
  botify_server:
    build: ./apps/botify_server
    container_name: botify_server
    ports:
      - "8000:8000"
    env_file:
      - ./apps/credentials.env
    volumes:
      - ./apps/botify_server:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - botify_net

  botify_cli:
    build: ./apps/botify_cli
    container_name: botify_cli
    env_file:
      - ./apps/credentials.env
    volumes:
      - ./apps/botify_cli:/app
      - ./apps/chat_history:/app/chat_history
    environment:
      - API_BASE_URL=http://botify_server:8000
    depends_on:
      - botify_server
    # Interactive mode
    stdin_open: true
    tty: true
    networks:
      - botify_net

  otelcol:
    build: ./apps/otel_col
    container_name: otelcol
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    env_file: ./apps/credentials.env
    volumes:
      - ./apps/otel_col/otel_config.yaml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP http receiver
    networks:
      - botify_net
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/jaeger:2.5.0
    container_name: jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # Jaeger collector HTTP endpoint
      - "14250:14250"   # Jaeger collector gRPC endpoint
      - "6831:6831/udp" # Jaeger agent port (UDP)
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    networks:
      - botify_net

volumes:
  chat_history:
    driver: local
    
networks:
  botify_net:
    driver: bridge