receivers:
  otlp:
    protocols:
      http:
        include_metadata: true
        endpoint: 0.0.0.0:4318
      grpc:
        include_metadata: true
        endpoint: 0.0.0.0:4317

processors:
  batch: {}

exporters:
  # We use the OTLP exporter to send data to Jaeger over gRPC
  # on port 4317 (the default OTLP gRPC port).
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      exporters: [otlp/jaeger]
    logs:
      receivers: [otlp]
      exporters: [otlp/jaeger]